version: '3.8'

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.secret
  wp_mysql_password:
    file: ./secrets/wp_mysql_password.secret

services:
  db:
    image: mariadb
    container_name: wp-db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db
    restart: always
    secrets: 
      - mysql_root_password
      - wp_mysql_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD_FILE=/run/secrets/wp_mysql_password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    secrets:
      - wp_mysql_password
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=db
      - WORDPRESS_DB_USER=dbuser
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/wp_mysql_password
    volumes:
      - ./wp-data:/var/www/html/wp-content
    networks:
      - wp
      - db
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.wordpress-secure.entrypoints=websecure"
      - "traefik.http.routers.wordpress-secure.rule=Host(`test2.dsvtranslations.com`)"
      # - "traefik.http.routers.wordpress-secure.service=wordpress-service"
      # - "traefik.http.services.wordpress-service.loadbalancer.server.port=80"

volumes:
  db-data:
    name: wp-db-data
networks:
  db:
    external: true
  wp:
    external: true
