version: '3.8'

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.secret
  wp_mysql_password:
    file: ./secrets/wp_mysql_password.secret

services:
  db:
    image: mariadb
    container_name: wp-db # change for multiple instances
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - db
    restart: always
    secrets: 
      - mysql_root_password
      - wp_mysql_password
    environment:
      - TZ=$TZ
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD_FILE=/run/secrets/wp_mysql_password

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress # change for multiple instances
    secrets:
      - wp_mysql_password
    ports:
      - $WPPORTN:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=db
      - WORDPRESS_DB_USER=dbuser
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/wp_mysql_password
    volumes:
      - ./html:/var/www/html
    networks:
      - wp
      - db
    restart: always
#    labels: # uncomment labels only if on the same VM as Traefik (same Docker host)
#      - "traefik.enable=true"
#      - "traefik.docker.network=proxy"
#      - "traefik.http.routers.wordpress-secure.entrypoints=websecure"
#      - "traefik.http.routers.wordpress-secure.rule=Host(`$SUBDOMAIN$DOMAINNAME`)"
#      - "traefik.http.routers.wordpress-secure.service=wordpress-service"
#      - "traefik.http.services.wordpress-service.loadbalancer.server.port=80"

networks:
  db:
    external: true
  wp:
    external: true
